### ISSUE TITLE
afex results not shown

### ISSUE THREAD

**Issue by Scott-S-Hannah** [WillemSleegers/tidystats-Word-add-in#10]
Hi Willem, 

Hope you're well. 

Have previously been using the plugin with results derived from the 'afex' package but after updating to the dev versions of the plugin and R package I no longer see the statistics in Word add-in.

The .JSON file seems to be created fine but the Word add-in is unable to extract the statistics? 

![image](https://user-images.githubusercontent.com/52243444/97451463-aeb02680-192b-11eb-9960-2de42abe18d9.png)

**Comment by WillemSleegers** [comment]
Hey Scott-S-Hannah,

Thanks for letting me know! I restructured the way analyses are parsed with the tidystats R package but I have not yet applied that new structuring to afex analyses. This means I will have to update the R package to add support again for afex. Once the R package is updated, it should work in the Word add-in.

I'll create an issue on the R package GitHub and work on it tonight.

- Willem

**Comment by WillemSleegers** [comment]
Fixed! 

If you install the latest version of the R package (`install_github("willemsleegers/tidystats")`) then it should work.

Could you let me know whether it does?

**Comment by Scott-S-Hannah** [comment]
Working for me now. Thanks for fixing that so quickly Willem. Will make good use of it this week!

**Comment by WillemSleegers** [comment]
Sweet. I will close this then. Let me know if you need me to add support for other analyses.
