### ISSUE TITLE
Symbol is not inserted for new "statistic" values

### ISSUE THREAD

**Issue by gasparl** [WillemSleegers/tidystats-Word-add-in#19]
[This line](https://github.com/WillemSleegers/tidystats-Word-add-in/blob/ea1273eeaafef2829566a733a50aac90f1cb2d56/src/functions/insertStatistics.tsx#L73) specifies what happens if the `statistic.name` is `"statistic"`. However, within that if statement's body, the insertion is specified only for some specific cases (`F` and `t`), and there is no final `else` clause. So if there is any other "statistic" name (e.g. Kolmogorov-Smirnov tests, among many others), no symbol is inserted (the text starts with an equal sign).

I think this can be solved by simply removing the `if (statistic.name === "statistic") {}`. This is what I [did](https://github.com/gasparl/tidystats-Google-Docs-add-in/commit/58fdacf8ae46ff0be429be6b847bb5e2b9bd3083) for the Google Docs add-in and it now seems to work fine in all cases.

**Comment by WillemSleegers** [comment]
Fixed this.
