### ISSUE TITLE
Add df for chi squared statistics

### ISSUE THREAD

**Issue by gasparl** [WillemSleegers/tidystats-Word-add-in#20]
To add `df` values (if available) for all chi squared statistics, I suggest replacing [`statistic.symbol === "t" &&`](https://github.com/WillemSleegers/tidystats-Word-add-in/blob/ea1273eeaafef2829566a733a50aac90f1cb2d56/src/functions/insertStatistics.tsx#L75) with [`["t", "χ²"].includes(statistic.symbol) &&`](https://github.com/gasparl/tidystats-Google-Docs-add-in/blob/3521ab1dead6f1a5ea017299720ea516111f17ca/src/server/functions/insertStatistics.ts#L90).

**Comment by WillemSleegers** [comment]
Fixed this!
