### ISSUE TITLE
Big Fixes in Test Files

### ISSUE THREAD

**Issue by ncrossberg** [WillemSleegers/tidystats-Word-add-in#28]
- [x] ajex.json: p_value recording as .00 and <.001 inconsistently
- [x] hmisc.json: subtests for correlations do not have names
- [x] effectsize.json and effsize.json: inconsistent reporting of cohen's d and hogen's g
- [x] glm.json: 'z' doesn't appear when reporting z-test
- [x] htest.json: the following statistics don't appear: chi-squared, V, W, D, DFt, AB, Z, K^2, CMH
- [x] lm4.json: Missing subheadings 
- [x] lm4.json: t-statistic doesn't show t-symbol
- [x] lmer_test.json: no subheadings for the correlation pairs
- [x] lmer_test.json: chi-squared doesn't report name
- [x] lmer_test.json: F-test names doesn't report 
- [x] pairwise_htest: no section headings for pairs

**Comment by WillemSleegers** [comment]
@ncrossberg I think I fixed these issues. I updated the Word-addin hosted on Netlify so you should be able to see that the issues are fixed (also use the new test files from the R package).

Can you verify that it works for you as well and do a random check of some other tests?

**Comment by ncrossberg** [comment]
Hi Willem,Im not home all day today. Will check first thing tomorrow.Regards,NicolaOn Mar 18, 2023, at 9:19 PM, Willem Sleegers ***@***.***> wrote:﻿
@ncrossberg I think I fixed these issues. I updated the Word-addin hosted on Netlify so you should be able to see that the issues are fixed (also use the new test files from the R package).
Can you verify that it works for you as well and do a random check of some other tests?

**Comment by WillemSleegers** [comment]
On purpose. Not all tests return degrees of freedom in the case of multilevel models.
