### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by jhualee** [WillemSleegers/tidystats-Word-add-in#40]
What is the node version and npm version used by this project?

**Comment by WillemSleegers** [comment]
I have node v20.7.0 and rpm 10.6.0 installed. What is the problem?

**Comment by jhualee** [comment]
> I have node v20.7.0 and rpm 10.6.0 installed. What is the problem?

Ok, thank you. I have already started the project. Now I am learning to make a word add-in plug-in. I will learn from your project.

**Comment by jhualee** [comment]
> I have node v20.7.0 and rpm 10.6.0 installed. What is the problem?

Hello, I would like to ask about the word add-in plug-in and how to deploy it to appSource.

**Comment by WillemSleegers** [comment]
Sorry jhualee, but those questions can be addressed via the documentation (for example, here: https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish). I am reserving this repo for issues specific to my tidystats software.
